### ISSUE TITLE
Document why SetPeers() is unsafe

### ISSUE THREAD

**Issue by F21** [hashicorp/raft#156]
The documentation for `SetPeers()` mentions that the operation may be unsafe: https://godoc.org/github.com/hashicorp/raft#Raft.SetPeers

However, it does not say why it is unsafe. It would be nice if the why is documented as well.

**Comment by s-christoff** [comment]
Hey @F21, thank you so much for bringing this up! This issue was reported on a version of Raft that is quite old. We removed `SetPeers()` awhile back, that is [here](https://github.com/hashicorp/raft/commit/687db02). Based on the volume of changes since that version we encourage you to try reproducing with the latest version of Raft. If you feel the issue is critical and on an older version of Raft, or still exists in the current version, do feel free to let us know and we can re-open it.
