### ISSUE TITLE
Dispatch a noop to the FSM from non-FSM logs

### ISSUE THREAD

**Issue by slackpad** [hashicorp/raft#166]
Kick the FSM for every log entry via a noop - see [these comments](https://github.com/hashicorp/raft/pull/134#discussion_r70161548) for details

**Comment by ongardie-sfdc** [comment]
So, these entries only have to reach the runFSM() function, not necessarily the FSM itself. That makes the change pretty simple, and my patch ongardie/hashicorp-raft@f0fc477 implements it easily by deleting some code. However, there are remaining issues.

This breaks the unit tests that check for ErrNothingNewToSnapshot. That error could mean one of two things:
 1. runFSM's lastIndex == 0, so why bother taking a snapshot? In this case, it should be ErrNothingToSnapshot (without the "New"). And maybe that shouldn't be an error at all: we should be able to produce a fully valid snapshot with a lastIndex of 0.
 2. Or it could mean that lastIndex has not advanced since the last time a snapshot was taken, so it'd be a waste of time to snapshot again. That'd make sense given the name, but it's not what's implemented. And it might be at odds with #159 giving the user the ability to save snapshots externally.

Speaking of #159, this'll have a merge conflict with #159. If that change is slated for library-v2-stage-two, can you do a new PR that I can review? Better sooner than later to avoid such conflicts.

**Comment by slackpad** [comment]
I'll get the user snapshot stuff teed up here shortly. I'm leaning towards being able to snapshot with a lastIndex of 0 and even snapshotting whenever requested, even if there's nothing new. Consul has some low-level background stuff that commits logs so I don't think even idle clusters having nothing new to snapshot in practice. It seems like extra complexity in the Raft code for little gain.

**Comment by ongardie** [comment]
Cool, getting rid of ErrNothing(New)ToSnapshot sgtm.
