### ISSUE TITLE
Is it safe to implement buffered FSM.Snapshot() -> FSMSnapshot.Persist(sink SnapshotSink)?

### ISSUE THREAD

**Issue by JeanGolang** [hashicorp/raft#202]
Hello!

I'm really sorry  - it's sort of a question/may be an issue, I couldn't find the right place to ask this apart from here.
I was trying to figure out how to implement buffered/chunked snapshoting/persisting of the FSM to the FileSnapshotStore provided by the raft package. I came up with an idea of sending chunks of the database I grab in my FSM.Snapshot() implementation via the send side of a channel and grabbing these chunks and persisting them on the receive side of a channel inside my FSMSnapshot.Persist implementation  to the raft package implemented FileSnapshotStore sink.

My question is - will this type of Snapshot() and Persist() implementations work fine with the underlying hashucorp/raft consensus implementation?

If not, how do I go about this problem? I'm doing the snapshotting in chunks to avoid crashing the program if my database size is larger than RAM available.

Thank you a lot in advance!

**Comment by slackpad** [comment]
Hi @JeanGolang we made some improvements to allow this in the library-v2-stage-one branch, which is in use by Consul and Nomad:

https://github.com/hashicorp/raft/blob/library-v2-stage-one/future.go#L51-L59

That new interface presents an `io.ReadCloser` you can use to stream the contents of the snapshot. There's an example in Consul here that uses this:

https://github.com/hashicorp/consul/blob/master/snapshot/snapshot.go

We buffer to a temp file on the Consul side, but this lets us stream to disk instead of having an extra copy of everything in RAM.

**Comment by JeanGolang** [comment]
Thanks a lot for your response, slackpad!
