### ISSUE TITLE
IP address requirement in raft config

### ISSUE THREAD

**Issue by bbeaudreault** [hashicorp/raft#236]
I'm a user of https://github.com/github/orchestrator/ and we run it in kubernetes. I recently submitted https://github.com/github/orchestrator/issues/253 there after raft support was added. Apparently it's a limitation of hashicorp/raft that members of the raft group must be specified with IP addresses in the config.  This is a really unfortunate limitation, especially as people move to systems like kubernetes. 

In kubernetes a pod could be restarted or moved, which would cause it's IP address to change and the raft config to be wrong. The solution in kubernetes would be to create a separate 1-replica deployment per raft member, and each raft member have its own service with a cluster IP. This means a lot of extra and cumbersome configuration. The right way to do this if raft could be properly configured would be to have a single deployment per application, so you can scale up or down by editing 1 config.

Would it be possible to support dynamic CNAME resolution in raft config?

**Comment by derekperkins** [comment]
Any thoughts on this?

**Comment by slackpad** [comment]
The latest version of the Raft library manages servers by ID (like a UUID) instead of the IP for the primary mapping. There's a `ServerAddressProvider` interface you can use to implement a mapping from that to an IP up in your application logic ([here's the interface](https://github.com/hashicorp/raft/blob/7e9c4782c0cf859dbf9e88c53e775b3edda0fc63/net_transport.go#L107-L109)). Consul uses this to remap IPs on the fly based on information for Serf, which helps for cases like k8s where all the servers can get moved at once.

**Comment by otoolep** [comment]
@slackpad -- can you explain how the ID might be used, in case I don't follow? It's my working assumption that it basically allows nodes to change IP addresses, without any effect on the any pre-existing Raft consensus state. So as long as the ID that is passed to a node on start-up doesn't change, it won't matter if the IP address has changed (unlike the previous version of Raft). Is this correct? Presumably `ServerAddressProvider` is only for some optional functionality, that a user of the Raft module may not choose to implement.

This is all relevant to me as I am currently porting [rqlite](https://github.com/rqlite/rqlite) to the latest version of Hashicorp Raft. Finally being able to decouple nodes from the underlying network addresses will be very useful. It's happening here: https://github.com/rqlite/rqlite/pull/377

**Comment by JelteF** [comment]
I haven't used raft with changing ips, so we use the id differently.
Because you can use any string for the ID,  we use the format <ip>:<uuid>.
This is quite nice if you want to be able to reset a node and make it
rejoin the cluster all fresh. The uuid part makes it seem as a new node to
the cluster and the ip part is nice when only the id is shown somewhere.

**Comment by s-christoff** [comment]
Hey everyone, thank you so much for the great discussion here. We discussed something similar in #299 - and we recommend setting the ID to be something that is not tied to the machine therefore allowing it to persist through failures. 
To answer @otoolep question, it doesn't matter if the IP address changes, in previous versions it was tied to the ServerID, but in its current state the ServerID and IP are separated. 

I'm going to close this issue for now, feel free to keep the discussion going if you'd like! :)
