### ISSUE TITLE
Travis is failing because of go 1.6 not being supported by go-metrics

### ISSUE THREAD

**Issue by JelteF** [hashicorp/raft#251]
Maybe we should disable the 1.6 tests and test 1.8 instead because it contains `sort.Slice`. Another possibility is to vendor/pin go-metrics to some version before it broke 1.6 compatibility.

**Comment by freeekanayaka** [comment]
I submitted a trival fix for go-metrics a while ago (see https://github.com/armon/go-metrics/pull/60), unfortunately upstream has been totally silent.

Perhaps you could comment or add a reaction to the PR above? To see if we can awake upstream authors.

I'd really prefer if we could land this trivial fix instead of vendoring go-metrics, or even worse disable 1.6 tests, since I have code that can't move away from 1.6 for now (due to LTS in various Linux distributions).

**Comment by JelteF** [comment]
I commented on the PR, but until it's fixed I think its' best to remove the 1.6 test. It's useless at the moment anyway. This is why I created #255, to do so.

**Comment by freeekanayaka** [comment]
Thanks.

on a second thought, since with the release of Go 1.9 the 1.6 realease has now reached its EOL, I guess it'd be legitimate for either armon/go-metrics or hashicorp/raft to drop support entirely.

So +1 for me for closing this issue as wont-fix if you wish.
