### ISSUE TITLE
Difficult to observe for a new Leader

### ISSUE THREAD

**Issue by hsanjuan** [hashicorp/raft#254]
Since 1.0.0, the `LeaderObservation` type is gone (not sure about the reasons).

Without that, observations from a follower for leadership changes are trickier. Correct me if I'm wrong, but there does not seem to be a way now to wait for a leader, other than polling `.Leader()`. Right now, an `Observer` registered in a follower node which stays so after an election receives no clues that a leader has been elected.

**Comment by slackpad** [comment]
Sorry about removing that - it wasn't used internally within the Raft library anywhere, and I thought these were added originally just to support the unit tests, but didn't realize they were public interfaces. If you want to PR restoring it we can merge it back, otherwise I can revert https://github.com/hashicorp/raft/commit/b7e8a11b96add650933f0d9a2eccf9a0729c6125.
