### ISSUE TITLE
Deployment and Config strategies

### ISSUE THREAD

**Issue by prologic** [hashicorp/raft#257]
Similar to #236 (*perhaps superseding*) I'd like to start a discussion on deployment strategies of raft based distributed applications. I've been playing around with [prologic/dkv](https://github.com/prologic/dkv) a fork of [hraftd](https://github.com/otoolep/hraftd)

Right now you depoy by doing something naive like this:

```#!bash
# Spin up first node
./dkv -id node1
./dkv -id node2 -join node1:11000
./dkv -id node3 -join node1:11000
```

**NB:** This assumes you are running each instance on a separate machine/container with different IP addresses and `node[N]` is resolvable (*somehow*).

In an ideal world you would:

```#!bash
for i in $(seq 0 1); do ./dkv -tier my-tier; done
```

Where `-tier my-tier` is some kind of service discovery.

Now -- There is consult and etcd however both I find somewhat *overkill* in the simple case and it would be nice if I could find a library with some well-defined interfaces that had pluggable "service discovery".

I'm also wanting to find out how others have architecture their raft-based applications. Configuring your nodes via command-line flags is "okay" but is not scalable.

**Comment by JelteF** [comment]
The thing I'm building is a distributed database. In my opinion it's not bad to configure nodes through a CLI, because adding and removing nodes is not a common operation. If at any point it becomes an issue we can use startup scripts on machines to register them automatically.

Regarding service discovery, we simply use a DNS A record with multiple entries, one for each node in the cluster. It's simple but very effective. We let the client loop over all addresses until it finds the leader. As an optimization we let followers return a leader if they know one and the client will try to connect to that one first.

**Comment by prologic** [comment]
@JelteF Good points. Let's be sure to keep this discussion to "deployment" and not "client's service discoverability" (*which is a separate issue*).

Whilst CLI configurable of setting up and maintaining a cluster is fine; how do you cope with machine moves, maintenances, repairs, etc? In a larger ecosystem managing this may be more operational work then at first thought?

At the simplest; one idea I had was to use DNS to discovery other noes to join the cluster. If the DNS lookup yields empty assume and become the leader. That way a `docker-compose.yml` might look like:

```#!yaml
version: "3.3"

services:
  my-dkv-cluster:
    image: ...
    command: -data /data -join my-dkv-cluster /tmp
    networks:
      - dkv
    volumes:
      - dkv:/data
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 3

networks:
  dkv:
    driver: overlay

volumes:
  dkv:
    driver: local
```

**Comment by otoolep** [comment]
I think about this issue a lot, due to my work on [rqlite](https://github.com/rqlite/rqlite), which uses the Hashicorp Raft module, like hraftd does. Using Kubernetes and containers also seems very promising to help with all this, though I have not tried it yet.

I have also considered TCP or UDP broadcast strategies, allowing nodes to find each other without needing a central discovery service (though I did [build one for rqlite](https://github.com/rqlite/rqlite/blob/master/DOC/DISCOVERY.md)). Someone from the community also [suggested using a zeroconf-based approach](https://github.com/rqlite/rqlite/issues/364). All this would require new code in rqlite.

Any of these solutions should work well when it comes to automatically adding nodes, but removing failing nodes requires an explicit "delete node" step (at least on Hashicorp Raft pre v1.0). That would need further work to automate.

**Comment by urjitbhatia** [comment]
If anyone is still looking at this, I attempted to make a simple wrapper with zeroconf here: https://github.com/urjitbhatia/autoraft

**Comment by ncabatoff** [comment]
https://github.com/hashicorp/go-discover is our answer to how to do pluggable service discovery.  I don't anticipate integrating with that library in hashicorp/raft directly, as all our raft-using products are already doing so at a higher level.
