### ISSUE TITLE
What is CommitTimeout for?

### ISSUE THREAD

**Issue by stapelberg** [hashicorp/raft#28]
CommitTimeout is set to 50ms by default, and I notice that the leader sends RPCs to all followers in that interval. config.go says “Time without an Apply() operation before we heartbeat to ensure a timely commit”, but I am having trouble finding the necessity of such a timeout/forced AppendEntries RPC in the raft paper.

Could you clarify what this is for please? Is it a performance optimization only? What is the recommended value to set it to (is there a rule of thumb)? What will happen when I set it to e.g. 10s, while not changing any of the other timeouts?

Thanks!

**Comment by armon** [comment]
Yeah, it's a subtle detail of how we've implemented raft. It's from section 5.3 on log replication. For a number of reasons, we do the heartbeats async from the AppendEntries with actual log data. Mostly it's to avoid head of line blocking on network and disk. Because of this decoupling, heartbeat does not include the `leaderCommit` value (highest committed index), since the replication may be lagging (any number of reasons). We only send that value in the replication stream. As a result, suppose I commit log at index 10. If there is no more write operations (e.g. nothing at index 11), then there is no way to update the `leaderCommit` of the followers. We use a `CommitTimeout` to instead replicate no logs, but to update the `leaderCommit` of the followers. In practice, it works the same as doing it in the heartbeat, but we avoid a number of other issues in favor of higher stability.

**Comment by stapelberg** [comment]
Thanks for clarifying that. I’m still wondering, though: wouldn’t it be enough to trigger _one_ additional AppendEntries after a successful commit to get `leaderCommit` to the followers, instead of sending 20/s (default setting)? :)

**Comment by armon** [comment]
Indeed. We used to do that :) But in practice you get all sorts of fun situations like a user restarting Consul in a way that causes data loss (e.g. replication log moves backward in time). With the no-op optimization we end up missing that and stalling the replication. Doing the AppendEntries is relatively cheap.
