### ISSUE TITLE
raft: Failed to get previous log: 4 log not found (last: 0)

### ISSUE THREAD

**Issue by Colstuwjx** [hashicorp/raft#280]
Hi team,

I'm testing raft library with [this demo](https://github.com/otoolep/hraftd.git)，and found that the follower would output some warning log:

```
2018/03/01 16:02:00 [WARN] raft: Failed to get previous log: 4 log not found (last: 0)
```

Is it means that  part of raft replication log lost?  But the demo kv-store operations, both `GET/POST keys` are OK..

**Comment by s-christoff** [comment]
Hey @Colstuwjx , 

Thank you so much for this question. I went ahead and walked through that demo as well and I saw that error appearing whenever I had a new node join the cluster, are you also seeing the error then? 

What I saw happening was that when the new node joins it becomes a follower and then this [test](https://github.com/hashicorp/raft/blob/master/raft.go#L1072-L1075)  is ran on the follower to check for conflicting log entries. This is a natural function of Raft which is used in log replication, where the leader checks the previous logs before appending any new entries. This is useful for when a follower may leave and rejoin the cluster with stale state. In this case, with a new follower, it is checking the follower’s log entries against the leader’s current log before appending any entries to the follower’s log. It sees there are no previous log entries since the follower is brand new. This triggers sending all the previous logs to the new follower.  This is expected with new nodes, and not something to worry about!

**Comment by Colstuwjx** [comment]
Got it, thanks!
