### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by ariesdevil** [hashicorp/raft#282]
So what is this? Is it really needed? https://github.com/hashicorp/raft/blob/v1.0.0/replication.go#L133

**Comment by s-christoff** [comment]
Howdy, great question! 

I would recommend checking out [this](https://github.com/hashicorp/raft/issues/28) issue for some background. `CommitTimeout` updates the `leaderCommit` (highest committed index) of the followers. 

This is necessary because the heartbeat function doesn't update the `leaderCommit` to preemptively mitigate any potential issues that could be caused like an increase in disk i/o or network latency. So, we periodically resend the `leaderCommit` when there are no new logs to make sure all the followers are up to date.  

I agree that this comment is a little confusing, I'll update this to make it a bit more clear. :)

**Comment by ariesdevil** [comment]
Thanks very.
