### ISSUE TITLE
last contact is set due to a vote request?

### ISSUE THREAD

**Issue by james-lawrence** [hashicorp/raft#285]
why is last contact set when a vote request is received. it seems to have nothing to do with actual leadership. and seems incorrect. maybe I'm missing something but if a vote request is received (and granted) then that says nothing about contact with the leader node. as obviously that node may not end up elected.

```
func (r *Raft) requestVote(rpc RPC, req *RequestVoteRequest)
```

**Comment by mkeeler** [comment]
@james-lawrence This is intentional behavior. It took a little digging but the rationale for doing it is documented in this commit: https://github.com/hashicorp/raft/commit/30f065a0484bebbe2cc8322f380e71a443e8fc05

The short answer is that according to the raft spec a server should remain in the follower state as long as it receives valid RPCs from the leader or a candidate. When processing the RequestVote RPC we are being contacted by a candidate and thus need to prevent attempting to gain leadership. If we did not reset the last contact time the heartbeat timer could elapse and we could initiate a leader election.

**Comment by james-lawrence** [comment]
@mkeeler then may I suggest separating out the two timestamps? particularly because the API explicitly claims last leader contact, not last candidate or leader. as a result the API is misleading.
