### ISSUE TITLE
How is performance?

### ISSUE THREAD

**Issue by minxinping0105** [hashicorp/raft#293]

**Comment by kleijnweb** [comment]
I have similar concerns. I haven't done any benchmarks, but here at least is a log fragment from one of my tests. There's no significant other latency here, nodes running in goroutines (and InmemStore):

```
time="2019-02-11 00:00:57.004902" level=debug msg="storing"
time="2019-02-11 00:00:57.006313" level=debug msg="applying to FSM"
time="2019-02-11 00:00:57.076133" level=debug msg="applying to FSM"
time="2019-02-11 00:00:57.097112" level=debug msg="applying to FSM"
```
This is a bit too high for my taste, but for my use case I can probably use a write buffer and write multiple messages as a single log entry.

**Comment by RobbieMcKinstry** [comment]
I think we should publish some benchmarking data in the README.

**Comment by RobbieMcKinstry** [comment]
@kleijnweb I don't anticipate that we're going to be making performance improves in the near future. However, I suspect we'd accept any PR for performance that results in equally readable and equally modular source.

I think it's fair to say that this Raft implementation has been used in clusters with nodes on the order of tens of thousands, so that's at least some indication of scalability.

**Comment by RobbieMcKinstry** [comment]
@banks do you have any direction for writing performance benchmarks for this Raft lib? I've seen the `/bench` directory, but I can't seem to find any source that makes use of it.

**Comment by RobbieMcKinstry** [comment]
This exists: https://coreos.com/blog/performance-of-etcd.html

**Comment by banks** [comment]
I'd be a little wary of including performance numbers in the readme. The answer is always "it depends".

I'd also be cautious about PRs with performance improvements that are not discussed first. Not because the lib is perfect by a long way - I know of at least 3 major ways we could improve throughput here but they all come with tradeoffs of some kind and/or threaten the correctness invariants of Raft unless extremely thoroughly considered.

For example there are several optimisations described in Diego's full thesis on Raft that we don't implement yet which would be good to at some point and would potentially be mergeable because they are based on solid design thinking and modelling work. Whereas PRs with less thought that just seem to improve a benchmark may be much harder to have confidence in.

Also the actual disk persistence mechanisms are pluggable and the ones provided here (boltdb-based log and file-based snapshots) are likely not the best performing.

> This exists: https://coreos.com/blog/performance-of-etcd.html

Yeah Etcd's benchmark is an interesting tool - I've played with it and not yet got it to run properly but it's a good place to start if you care. There are a few big caveats I'd make about the report:
 1. The benchmark is optimized towards large KV stores (2GB, million KVs) and extremely high write throughput. That's not invalid as that's one legitimate use case but it's not the one _Consul_ is optimised for.
 2. The performance pathology there are really due to _Consul's_ design choices - to dump the entire snapshot to disk periodically rather than persistently store the whole DB and only make incremental changes. That obviously causes issues under that load but it's not inherently a limitation of this raft library. Other HashiCorp products are already building on this library but using a persistent store that won't have the same problem and will likely be much closer to etcd's performance profile in that benchmark. Consul may change this at some point however we don't observe this kind of performance pathology enough in the real world to have prioritised it above other work yet although I'm personally interested.

**Comment by RobbieMcKinstry** [comment]
After sidechanneling with @banks, we're thinking about two sets of microbenchmarks -- 1. set of benches for totally in memory, no network 2. for actually using the boltdb logs, snapshotting, and persisting to disk.
No guarantee this will happen though. After reading his response, I'm totally in agreement: benchmarks will always be misleading because ultimately the FSM is going to be a huge factor in performance. iops are almost always the limiting factor in Raft performance.
