### ISSUE TITLE
FAIL: TestNetworkTransport_AppendEntriesPipeline_CloseStreams

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/raft#296]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907764,
`TestNetworkTransport_AppendEntriesPipeline_CloseStreams` fails as follows:

~~~~
--- FAIL: TestNetworkTransport_AppendEntriesPipeline_CloseStreams (0.01s) 
        raft_test.go:101: 04:01:44.428789 [DEBUG] raft-net: 127.0.0.1:38795 accepted connection from: 127.0.0.1:50048 
        net_transport_test.go:430: expected an error due to the streams being closed 
~~~~

Easily reproducible...

**Comment by s-christoff** [comment]
Hey @onlyjob , Thank you so much for this! Sadly, the test suite for this library are nondeterministic and timing sensitive and therefore sometimes give unpredictable results. This is an area we would love to improve and accepting PRs!

**Comment by onlyjob** [comment]
So why this bug report is closed? Is it fixed?

**Comment by s-christoff** [comment]
Hey @onlyjob, Apologies for the confusion on this! This bug is not fixed - however we are closing this for now due to the large restructuring of the testing suite that would be required to remove any nondeterministic or timing sensitive tests. It is something we hope to fix overtime, and have been receiving PRs which we are reviewing currently for, but we have no plans currently to rework the testing suite. We’d welcome any contributions to making this or any other specific tests more reliable.
