### ISSUE TITLE
Support Pre-Vote optimization

### ISSUE THREAD

**Issue by armon** [hashicorp/raft#31]
Use a pre-vote to avoid disrupting a stable cluster when possible

**Comment by icexin** [comment]
I used to implement a raft in c++. In this version, before election, the candidate send a query to others to check whether the leader is alive, when receives  enough positive answers, then starts sending votes.
However, this optimization may delay the discovery of leader failure, since everyone must wait until majority of followers is timeout.
Hope this helps.

**Comment by slackpad** [comment]
See section 9.6 for more details - https://ramcloud.stanford.edu/~ongaro/thesis.pdf.

**Comment by komuw** [comment]
https://blog.cloudflare.com/a-byzantine-failure-in-the-real-world/   
<img width="1185" alt="Screenshot 2020-11-28 at 18 47 14" src="https://user-images.githubusercontent.com/5163857/100519614-2df27d80-31aa-11eb-829e-7058f9fa90cd.png">

**Comment by dhiaayachi** [comment]
Fixed by #530
