### ISSUE TITLE
FAIL: TestRaft_SendSnapshotFollower

### ISSUE THREAD

**Issue by YNX940214** [hashicorp/raft#311]
The behind server blocks in about line 1028 in raft.go: rpc.Respond(resp, rpcErr).

**Comment by s-christoff** [comment]
Hey @YNX940214  - 
Thank you so much for bringing this up. Are you able to expand on the error or issue you are encountering? Logs, replication steps, and as much detail as you can provide would be appreciated so we can help you as thoroughly as possible.

**Comment by YNX940214** [comment]
I run "make test" and find several tests failed. Then I added some logs to the code and run 
"go test -v -timeout=60s -run TestRaft_SendSnapshotFollower | tee log3".

I track the problem by adding logs in the following procedure:
In raft_test.go line 195 the fall behind server's ShutdownFuture's "Error()" blocks.
In state.go line 151 "r.routinesGroup.Wait() " blocks.
In raft.go line 136 "r.runFollower()" blocks.
In raft.go line 154 "r.processRPC(rpc)" blocks.
In raft.go line 964 "r.appendEntries(rpc, cmd)" blocks.
In raft.go line 1012 "rpc.Respond(resp, rpcErr)" blocks.

I have logs, but I don't know to how upload it on github.

**Comment by s-christoff** [comment]
Hey @YNX940214 ,

Thank you for providing that information. I was also seeing issues with running `make test` or `go test -v -timeout=60s` as well. 
I believe this may be related to issue #312 where the Raft.Shutdown is hanging because there is no timeout specified for sending an RPC in our tests, only receiving. #313  should now fix this, so feel free to pull it down and test. If you have any other troubles just re-open this issue or create a new one if you see a new problem occurring.
