### ISSUE TITLE
Disk based FSM

### ISSUE THREAD

**Issue by Iulian7** [hashicorp/raft#396]
What is the best practice for implementing a disk based FSM (e.g. Bolt, Badger, Pebble, etc)? 

- How would snapshotting work? With a large database it would not be possible to take frequent snapshots as it would take too long. 

- Node restart: how can we make use of the disk persistence to start up nodes efficiently? The latest snapshot + following entries are replayed when a node restarts. However, with a large disk based FSM, this would take a very long time and is not practical. In reality only a few log entries need to be replayed (the ones missed while the node was down) unless the node's disk crashed and it is blank or the node has been offline for a very long period of time. 

To make this work:
1. Always persist `lastLogIndex` in the DB. 
2. Can we safely ignore `FSM.Apply` and `FSM.Restore` if we already have a higher log index locally (`lastLogIndex`)? 
2. Is it safe to simply write `lastLogIndex` when `FSM.Snapshot` is called and when `FSM.Restore` is called we go to one of the nodes with a new enough DB (`lastLogIndex >= requestedSnapshotIndex`) and download the **whole** DB (even if it is newer than the snapshot being asked for)?
3. Are there any other caveats I am not seeing?

**Comment by tomqwpl** [comment]
Yes, I also have this question.
The ConfigurationStore interface seems to suggest that an FSM that mutates a durable store is something that is sensible/supported. There is also the option to not restore a snapshot on startup. I don't know enough about Raft to reason about what you'd need to do though at the moment. 
Logically, a snapshot is a replacement for a sequence of log entries. So rather than applying all log entries, start form the latest snapshot then apply only the remaining log entries.
However, the persistent state of the FSM might be ahead of the snapshot, so care is required not to apply log entries to the FSM that you've effectively already got. 

Consul is in memory, so that can't be used as a reference here. 
However, if a new node is added to the cluster, it's going to get sent the latest snapshot and any log entries, so on the face of it the snapshot does have to be self contained, it can't just rely on the metadata I don't think.

I think some clear guidance on this would be super helpful, or a reference implementation of a simple persistent key value store. The only example I've seen (rqlite) literally snapshots the complete sqlite database file, which is at least simple and correct.

**Comment by tomqwpl** [comment]
I've been studying the Vault use of Raft. It uses a persistent BoltDB. You can see it [here](https://github.com/hashicorp/vault/blob/master/physical/raft/fsm.go).
Not sure I understand the implementation yet, but it ought to be a good reference.
