### ISSUE TITLE
Use of break in replication.go

### ISSUE THREAD

**Issue by aprimadi** [hashicorp/raft#410]
https://github.com/hashicorp/raft/blob/ae3f4f2e0ae5e88dab8c9f6dc2521a45121f9a2a/replication.go#L426
https://github.com/hashicorp/raft/blob/ae3f4f2e0ae5e88dab8c9f6dc2521a45121f9a2a/replication.go#L432

Why use break statement in these two lines while setting `shouldStop = true` achieve the same thing?

**Comment by s-christoff** [comment]
Howdy @aprimadi  - 
As it is, you are correct that `shouldStop = true` would achieve the same thing. I think that it was more of an arbitrary design decision and `break`s were just the authors preferred choice. However, I think it is good they are used because it’s more explicit that you want to exit the loop without any further logic - for example if any more logic was added after the switch in the loop break would skip it but boolean would not.
