### ISSUE TITLE
New node not receiving raft.Configuration after leader calls AddVoter

### ISSUE THREAD

**Issue by smartin015** [hashicorp/raft#534]
Consider the following:

`Node A` constructs a new Raft instance, calling `BootstrapCluster` to provide an initial server list consisting just of itself (no other nodes). The log output looks like this:

```
raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:A Address:A}]"
```

Some time passes and now I want to add `Node B` as a voter. `B` has never participated in the quorum and has no logs/snapshots/other persisted state - it's a clean slate. 

From what I've gathered, I need to call `AddVoter` on `A`. I do this and get the following log output:

```
raft: updating configuration: command=AddVoter server-id=... server-addr=... servers="[{Suffrage:Voter ID:A Address:A}{Suffrage:Voter ID:B Address:B}]"                 
raft: added peer, starting replication: peer=B
```

It seems that the change is accepted. But now AFAIK I should not call `BootstrapCluster` with `B` as as it would conflict with the newly commited `Configuration` of `A`, which has the state we want (`A` and `B` in a happy little quorum). 

I'm using `Libp2pTransport` as a transport layer. I set up `B` with a `raft.Transport` that has `A` in its `peerstore`, and do the same with `B` in `A`'s peerstore:

```
hostA.Peerstore().AddAddrs(b.ID, b.Addrs, peerstore.PermanentAddrTTL)
```

And then calling `NewRaft()` on `B`, I get the following on `A`:

```
raft: failed to contact: server-id=B time=501.412479ms                              
raft: failed to contact quorum of nodes, stepping down
```

And on B:

```
raft: initial configuration: index=0 servers=[]                                                                                        
Assignment succeeded; type now  ELECTABLE
```

If I instead try to also bootstrap `B` with both nodes in the `servers` part of `Configuration`, I get this on `A`:

```
raft: appendEntries rejected, sending older logs: peer="{Voter B B}" next=2
raft: pipelining replication: peer="{Voter B B}"
```

And this on `B`:

```
raft: entering follower state: follower="Node at B [Follower]" leader-address= leader-id=
raft: failed to get previous log: previous-index=3 last-index=1 error="log not found" 
```

Can you tell what's going wrong here?

**Comment by mpalmi** [comment]
raft nodes start as followers when configured correctly. They then wait for the leader to talk to them, at which point they can correctly identify the leader and start streaming logs.

The logs you're seeing seem consistent with this:

* `raft: entering follower state: follower="Node at B [Follower]" leader-address= leader-id=`, `B` is in a follower state and has not yet heard from the leader, which is why you're seeing an empty `leader-address` and `leader-id`.

* `raft: failed to get previous log: previous-index=3 last-index=1 error="log not found" ` is an expected log from `appendEntries` on empty follower nodes. The follower also includes information in its response about what state it has. The leader will send the correct state after this point to catch the follower up.

Are you seeing any further issues after this point? Or is there some reason to think this might not be a healthy state?

**Comment by mahditakrim** [comment]
I have kinda same problem with the logs, can't see 'leader-address' and 'leader-id' to have value at all !

**Comment by ncabatoff** [comment]
The described behaviour is what we expect to see.  Closing as not-a-bug.  We'll reopen given more details.
