### ISSUE TITLE
Is there a way to make Snapshotting optional?

### ISSUE THREAD

**Issue by JoanFM** [hashicorp/raft#539]
I am wondering if there is a way to make `Snapshot` logic optional, meaning that no Log Compaction happen and every replication and restoring is done by reapplying the Logs.

Is there an option here? Maybe in the Snapshot interface, an error should be returned?

**Comment by banks** [comment]
This isn't really supported today because in general a system with logs that grow for ever isn't very practical. Even if you never anticipate running out of disk space for logs, the time taken to recover on each startup will grow linearly with time. So you basically guarantee that eventually the system will fail and need manual intervention to recover to a state that works again.

Can you give any more detail on what your use-case is that never requires snapshots?

All that said, if you are just testing things out and don't want to bother with making snapshots work, you can just configure `SnapshotThreshold` to be bigger than the total number of logs you will ever write and get the same effect.

**Comment by JoanFM** [comment]
Hey @banks,

Thanks for the response, this is what I thought. In my case, it was more a question to simplify the system for small scale.

Also I have seen that if the FSM fails to snapshot, it can still work as if it was not given
