### ISSUE TITLE
Why after calling RemoveServer for a node does it still continue to heartbeat it?

### ISSUE THREAD

**Issue by andrew-delph** [hashicorp/raft#564]
After calling RemoveServer on a node that has been killed the logs are indefinitely spamming.

failed to contact server: xyz....
failed to contact server: xyz....
failed to contact server: xyz....

For context I am trying to set up the cluster to achieve consensus for a simple counter variable. I am also trying to automatically manager this cluster. I want it to add and remove nodes as they come online.

Can anyone provide some pointers on this as I am lost.

**Comment by otoolep** [comment]
I'm not sure what "RemoveServer on a node that has been killed" means, because if the node has been killed, how do you call "RemoveServer" on it? I presume what you mean is that you call "RemoveServer" on the Leader after killing the node (assuming the node you killed is not actually the Leader, in that case you must wait for a new Leader to be elected).

RemoveServer will work, and the Leader should stop attempting to contact the node that you killed. It can take a few seconds. Also, perhaps RemoveServer didn't actually work. You need to understand that RemoveServer requires consensus to be reached before the removal can take effect. If you have a two node-cluster, kill one of the nodes, then call RemoveServer on the other node that is still up, the node can't be removed from the cluster configuration -- because consensus can't be reached on a 2-node cluster where one node is down i.e. killed.

Try a 3-node cluster, kill a node, and call RemoveServer on the node that is Leader. It will work.

You could look at [the docs for rqlite](https://rqlite.io/docs/clustering/general-guidelines/#removing-or-replacing-a-node), which discuss this in detail. rqlite uses the Hashicorp Raft library.

**Comment by andrew-delph** [comment]
Hello @otoolep,

Thank you for the response. I found out that there was a bug is my code causing the issue.

I will be referencing rqlite as it is very detailed and along the same lines of what I am trying to do but in more detail.
