### ISSUE TITLE
Panic brain-split in appendEntries call

### ISSUE THREAD

**Issue by nopnoping** [hashicorp/raft#568]
Hello team. 
I'm confused about this: https://github.com/nopnoping/raft/blob/main/raft.go#L1393.
It will be follower when the state is leader and the term equals requester term, but this situation is a brain-split which should panic an error. Although it may never happen, explicitly panic brain-split error may better.
Like this: https://github.com/nopnoping/raft/blob/opt_appendEntries/raft.go#L1391-L1402

**Comment by banks** [comment]
Hi @nopnoping, I can see your logic there but that's not actually how the raft protocol (or any consensus protocol I know of works).

It's in general impossible to perfectly solve the distributed leader election problem in a real network (this is called the FLP result in literature) and neither Raft nor Paxos makes the guarantee that "at most one node will consider itself to be leader at any time". To put this another way: "split brain" suituations are **enevitable** in real world situations and the correctness of a consensus protocol is not in avoiding that happening entirely, but rather ensuring that _when it does, nothing bad happens in the system_.

In other words if we panic in the case your PR does **we will break raft!**. That's because systems _can and do_ get into a situation where for a short time, two nodes think they are the leader. I've been testing this exact scenario in Vault for the last few months - it's really easy to get into and we see it in production too. In those cases, your PR would cause one or both of the nodes to crash, making the whole system unavailable. The whole point of raft is correctly tolerate this situation and having one node crash is not that! At best, your added panic will make it take significantly longer for the cluster to get back to a healthy state (and cause scary logs that will cause operators great concern too). At worst, it could destroy the availability of the cluster and potentially force a manual recovery (though that would be more rare).

Here's an example of how this can happen:

 1. imagine a 3 node cluster with nodes A, B, C
 2. node A is leader and all is healthy
 3. at time t1 node A is suspended - perhaps someone paused the container to migrate it, hit ctrl-z or just the CPU is suddenly hammered by some other process and so it gets no CPU time for a few seconds all of these are plausible!
 4. node B hits it's Heartbeat timeout first and becomes a candidate and gets elected by a vote from C
 5. node A un-pauses (gets scheduled on the CPU again).

At this point, both nodes A and B think they are the leader although B has a higher term. (Notice since A was suspended and not just partitioned it never stepped down since it's own LeaderLease timer has not fired yet).

The current behaviour, following the Raft paper, is that on Node A one of these things will happen first:
 1. It's leader lease timeout fires and it's not had heartbeats while it was suspended so "steps down"
 2. it tries to send a heartbeat to B or C and gets a "you've not got the highest term" response and so steps down
 3. it tries to complete writing a value that was in flight when it paused (this is actually the same as sending a heartbeat above since both are just `appendEntries` calls) but the node it talks to will reject it and inform it of the higher term causing t to step down (and the write to fail).
 4. the new leader manages to connect to it and start trying to `appendEntries` with a higher term (this is the case that code you linked to handles). since it sees another leader exists with a higher term, it immediately steps down.

In all of the cases the behaviour is correct - the old leader notices it's not leader any more and steps down. Any writes it tries to complete in this state will fail because a quorum of other nodes already have a higher term and will ignore it.

Fundamentally it is the Raft term that makes this behaviour correct, not the assumption that at most one nodes believes it is the leader at any time.

With your change to introduce a panic, at best the old leader will panic, be restarted and come back as a follower - but that is strictly worse than the current behavior since it has to reload all its state from disk before it can instead of being able to become a follower almost immediately and just fix up the entries it missed. At worst, it doesn't come up at all or not for a few minutes because it takes so long to load the snapshot or because the operator hasn't configured systemd or similar correctly!

So I don't think that this is a problem and infact the proposed solution is strictly worse for the availability of the cluster and no better for correctness!

Does this make sense? If not I'm happy to elaborate or refer you to many great resources on why raft is correct that can explain better than me!

**Comment by nopnoping** [comment]
Hi @banks, thank you for your patient and helpful responses. I've learned so much from you and I truly appreciate your guidance.
