### ISSUE TITLE
How to know when all log entries are applied after app restart? 

### ISSUE THREAD

**Issue by kungf** [hashicorp/raft#602]
when candidate became the leader，then it began to apply logs after restart, how I waiting it apply all logs, and get my latest value?

**Comment by banks** [comment]
Hi!

You can do that using `raft.Barrier` https://github.com/hashicorp/raft/blob/a5db400428964844d4a148da83d17a192ced345f/api.go#L845-L850

You can see how it's used in Consul although it's a complex code base so it might take a little working through: https://github.com/hashicorp/consul/blob/5a74bb6d5a1e96ac3e94d55dd44660b2a29e4513/agent/consul/leader.go#L175

**Comment by kungf** [comment]
hi @banks i add a barrier, but it was handed when calling barrier.Error(), do you have any suggestion? thank you very much!!
```
              if t.HashicorpRaft.State() == hashicorpRaft.Leader {
                       barrier := t.HashicorpRaft.Barrier(10 * time.Second)
                      if barrier.Error() != nil {
                                return false
                    }
                          return true
                  }
```

**Comment by banks** [comment]
I'm not sure what you mean by "it was handed when calling barrier.Error()".

It's a little hard to tell without context where that code is running whether it will do what you need. In general you need to run this each time the leader is elected before it starts accepting any requests that assume up-to-date reads. In consul we have that leader loop that executes whenever raft notifies us that the current node has become a leader, and it waits for the barrier before it does any other "setup leader" stuff and before it will respond to writes or reads forwarded from other nodes.

Barrier doesn't guarantee anything about the _followers_ FSMs since one or more followers might not even be online and the cluster still has to work, all it does is perform a "no-op" dummy operation which is equivalent to a write and then wait until that operation is applied to the leader's own FSM which implies that all previous writes including those committed by older leaders are also applied.

**Comment by kungf** [comment]
sorry for typo "hanged"

**Comment by kungf** [comment]
fix using raft notify ,thank you @banks
