### ISSUE TITLE
Question about ReadIndex

### ISSUE THREAD

**Issue by TZY0101** [hashicorp/raft#603]
Does this library have an implementation of ReadIndex? I didn't find it in the source code

**Comment by banks** [comment]
I assume you're referring to Section 6.4 of the raft thesis about providing more efficient linearizable reads without a write to the log.

The answer is nuanced. Consul does implement something similar using this library, but it's not named identically as Deigo described in the thesis.

The short version is: you implement the steps in the thesis yourself in your app. Use `raft.Barrier` to acehive step 1 (assuming you don't already to this on a new leader before handling any read requests which is what Consul does) and use the `raft.VerifyLeader` at the crucial step 2 to check you still are the leader.

One intersting anecdote if you like spending time in the weeds is that for years I've suspected that they way Consul implements `consistent` reads is subtly wrong: in most cases we verify leadership first before performing the local read. I think if we did it the other way around it would be correct, but as it is there is a time between VerifyLeadership completing and the actual FSM read where it's just about possible that the leader could stall or have the process pauses for long enough that another leader could be elected and commit a write to the data being read. It's highly unlikely this will ever actually occur outside of an environment that is trying really hard to force it and we've never seen it in production or even in Jepsen and similar test environments.

If you are implementing from scratch I think you can implement something equivalent to the Thesis but even simple that is still correct (but you only have my non-peer-reviewed thinking and your own to rely on there):

 1. Ensure the leader has applied all previously committed FSM updates. You can do this with `raft.Barrier` either before accepting any reads as a new leader or at the time of the first (or every) strict read operation.
 2. Perform the read operation on the local FSM
 3. Issue a `raft.VerifyLeader`. If this comes back successfully you know that at the time of the read in 2 you must have been the leader still and due to 1 you had the most up to date state machine in the cluster. (Note that the state might have changed already due to a concurrent write by the time VerifyLeader completes but that's OK because the linearization point of the read came before the write and the order they are responded too can't matter or be relied on in an asynchronous network.
 4. Respond with the read value.

This is a little simpler than what's in the thesis, but as far as I can see it's equivalent and preserves Raft's correctness properties.

It's also worth pointing out that this is still pretty costly. At least reads done this way are consistent without causing disk IO, but they still have to wait for round trips to a quorum and currently `VerifyLeader` doesn't have any optimizations that would amortize that cost if there are many concurrent consistent reads - each would send it's own set of additional heartbeats to followers.

Hope this is useful.

**Comment by banks** [comment]
After some internal discussion, we realised that the implementation I described above it still potentially subtly wrong.

Currently, `VerifyLeader` takes no arguments which means it only verifies that at the time of the call the node is the leader and that no higher term has been seen by a quorum.

That means it's possible that you could have an execution like this, cluster nodes N1, N2, N3:

 1. Consistent read starts on N1, FSM is read at Term 1, Index 100
 2. N1 pauses - maybe overload or VM is moved or someone hit Ctrl Z
 3. Quorum elects a new leader N2, process a write at Term 2 Index 101
 4. N2 fails
 5. N1 unpauses
 6. N1 becomes leader again in Term 3
 7. N1 continues processing the consistent read from before (it had a long timeout!), calls `VerifyLeader`
 8. VerifyLeader will return successfully here because it is the leader in Term 3 even though an acknowledged write was made in term 2 that makes the read stale.

A fully correct solution would require that `VerifyLeader` could be passed the term at which the read occurred so it doesn't just verify we are leader, but leader in the same term as the read. Or alternatively that it should return the term in which the quorum agrees the leader was elected this way it would still depend on callers correctly checking it's the same term they started on but could allow correct use.

All this said, the situation in which this would produce an incorrect result would be very hard to generate even if you tried short of augmenting the code to artificially pause at the right time. I mention this for completeness. If you feel this is important for your use-case we'd consider a PR that adds something like a `VerifyLeaderInTerm` for this.
