### ISSUE TITLE
Can't get leader when I use certain config.

### ISSUE THREAD

**Issue by zey1996** [hashicorp/raft#604]
My config
``` go
	config := &raft.Config{
		ProtocolVersion:  raft.ProtocolVersionMax,
		HeartbeatTimeout: 30 * time.Second,
		ElectionTimeout:  30 * time.Second,
		CommitTimeout:    30 * time.Second,
		MaxAppendEntries: 64,
		ShutdownOnRemove: true,
		TrailingLogs: 3,
		SnapshotInterval:   600 * time.Second,
		SnapshotThreshold:  10,
		LeaderLeaseTimeout: 1 * time.Second,
		LogLevel: "debug",
	}
```
and I have 3 raft node. this raft cluster can't get leader when I run it. Here is the log.
[node3.log](https://github.com/user-attachments/files/16439524/node3.log)
[node2.log](https://github.com/user-attachments/files/16439525/node2.log)
[node1.log](https://github.com/user-attachments/files/16439527/node1.log)

**Comment by zey1996** [comment]
I know 30s is to long, but it's not banned, why it don't work?

**Comment by banks** [comment]
```
2024-07-31T17:19:15.459+0800 [INFO]  raft: entering leader state: leader="Node at 127.0.0.1:9400 [Leader]"
2024-07-31T17:19:15.459+0800 [INFO]  raft: added peer, starting replication: peer=node1
2024-07-31T17:19:15.459+0800 [INFO]  raft: added peer, starting replication: peer=node2
2024-07-31T17:19:15.459+0800 [INFO]  raft: pipelining replication: peer="{Voter node1 127.0.0.1:9401}"
2024-07-31T17:19:15.459+0800 [INFO]  raft: pipelining replication: peer="{Voter node2 127.0.0.1:9402}"
2024-07-31T17:19:16.701+0800 [WARN]  raft: failed to contact: server-id=node1 time=1.000260698s
2024-07-31T17:19:16.701+0800 [WARN]  raft: failed to contact: server-id=node2 time=1.000267498s
2024-07-31T17:19:16.701+0800 [WARN]  raft: failed to contact quorum of nodes, stepping down
```

The leader is getting elected but is failing to receive a heartbeat from either follower within the 1 second `LeaderLeaseTimetout` you set and so it's assuming that it is partitioned and stepping down.

I think the problem is that heart beats are sent at a rate that is determined by `heartbeatTimeout/10`. Because you set your heartbeat timeout to 30 seconds, that means the leader is only sending heartbeats every 3 seconds!

But the LeaderLeaseTimeout is 1 second so it will never get a heartbeat response before this and will always fail to maintain it's lease.

`LeaderLeaseTimeout` therfore needs to be larger than HeartbeatTimeout/10 and preferably a lot larger. The default values are 1 second HeartbeatTimeout and 500ms LeaderLeaseTimeout so ideally we should get 4 or 5 heartbeats in before the leader lease expires.

https://github.com/hashicorp/raft/blob/a5db400428964844d4a148da83d17a192ced345f/config.go#L311-L325

If you set `LeaderLeaseTimeout: 15 *time.Second` it should work, but FWIW I think these timeouts are far too long. Bear in mind that these are only the minimum - the real timeout is picked randomly between the value you set and 2x that value so a 30 second election timeout actually means that a node might go for 60 seconds without getting a heartbeat before it starts an election.

Finally, `TrailingLogs: 3` is likely to cause problems depending on your application. The subtlety is that while you don't _need_ those logs any more after a snapshot, any node that even temporarily disconnects for even a few seconds right at the point the leader takes a snapshot means that when it reconnects say 5 logs behind it will now need to do a full snapshot restore which means transmitting your entire dataset over the wire. Unless you data is tiny or your update rate so low that it's barely 1 every few seconds, that's likely to cause major performance and availability problems super fast.

But it gets worse: if you have a larger snapshot or a slow network and it takes more than 1 second to transmit the snapshot to the follower, install it, and start replicating logs again (very likely even with tiny snapshots!) then unless you have fewer than 3 writes occur in that second, or you get really lucky with timing, the follower will never be able to catch up! This is real and happens in Consul clusters in the wild even with 10k trailing logs. See more info here:  https://developer.hashicorp.com/consul/docs/agent/monitor/telemetry#raft-replication-capacity-issues

Our default in around 10k logs

**Comment by zey1996** [comment]
@banks 
Yes, in my application, event update rate is very low. in fact I use it to control my cluster status.
I notice the leader may be changed in some time, I guess some packet loss. I hope I can modify some argument to to avoid node disconnection/resurrection (my node is always online).

Last, Maybe we can add inspect. throw a panic if `heartbeatTimeout/10` > `LeaderLeaseTimetout` ?

**Comment by banks** [comment]
Yep that would be a useful check to add when validating config!
